config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "articles#index"
  resources :articles do 
    resources :comments, except: [:show, :index, :new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates_presence_of :title
    validates_presence_of :content

    has_many :comments, -> { order("id DESC")}, :dependent => :destroy
    belongs_to :user, :foreign_key => 'author_id'
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates_presence_of :content

    belongs_to :article
    belongs_to :user, :foreign_key => 'author_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :articles, -> { order("updated_at DESC")}, :dependent => :destroy
  has_many :comments, -> { order("updated_at DESC")}, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception, prepend: true
    before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, :only => [:edit, :update, :show, :destroy]
    before_action :current_user_is_author?, :only => [:edit, :update, :destroy]

    def index
        @articles = Article.includes(:user).page(params[:page]).per(5).order(updated_at: :desc)
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.author_id = current_user.id
        if @article.save
            flash[:notice] = 'Article has been created successfully.'
            redirect_to :action => :index
        else
            flash[:alert] = 'Article hasn\'t been created successfully.'
            render :action => :new
        end
    end

    def edit
        if  !current_user_is_author?
            flash[:alert] = 'You can\'t edit this article.'
            render :action => :show
        end
    end

    def update
        if !current_user_is_author?
            flash[:alert] = 'You can\'t edit this article.'
            return render :action => :show
        end
        
        if @article.update(article_params)
            flash[:notice] = 'Article has been saved successfully.'
            redirect_to :action => :show, :id => @article
        else
            flash[:alert] = 'Article hasn\'t been saved successfully.'
            render :action => :edit
        end
    end

    def show
        @comment = Comment.new
    end

    def destroy
        if !current_user_is_author?
            flash[:alert] = 'You can\'t delete this article.'
            return render :action => :edit
        end
        @article.destroy

        flash[:notice] = 'Article has been deleted successfully.'
        redirect_to :action => :index
    end

    private
        def article_params
            params.require(:article).permit(:title, :content, :author_id)
        end

        def set_article
            @article = Article.includes(:comments, :user).find(params[:id])
        end

        def current_user_is_author?
            current_user.id == @article.author_id
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_comment, :only => [:edit, :update, :destroy]
    before_action :current_user_is_author?, :only => [:edit, :update, :destroy]

    def create
        @comment = Comment.new(comment_params)
        @comment.author_id = current_user.id
        #@comment.article_id = @article.id
        logger.debug("qqqq_comment:" + @comment.author_id.to_s)
        if @comment.save
            flash[:notice] = 'Comment has been created successfully.'
            
        else
            flash[:alert] = 'Comment hasn\'t been created successfully.'
        end
        redirect_to article_path(@comment.article_id)
    end

    def edit
        if !current_user_is_author?
            flash[:alert] = 'You can\'t edit this comment.'
            redirect_back(fallback_location: article_path(@comment.article_id))
        end
        @article = Article.find(@comment.article_id)
    end

    def update
        if !current_user_is_author?
            flash[:alert] = 'You can\'t edit this comment.'
            return redirect_to article_path(@comment.article_id)
        end

        if @comment.update(comment_params)
            flash[:notice] = 'Comment has been saved successfully.'
            redirect_to article_path(@comment.article_id)
        else
            flash[:alert] = 'Comment hasn\'t been saved successfully.'
            render :action => :edit
        end
    end

    def destroy
        if !current_user_is_author?
            flash[:alert] = 'You can\'t delete this comment.'
            return redirect_to article_path
        end

        @comment.destroy

        flash[:notice] = 'Comment has been deleted successfully.'
        redirect_to article_path(@comment.article_id)
    end

    private
        def comment_params
            params.require(:comment).permit(:content, :article_id, :author_id)
        end

        def current_user_is_author?
            @comment.author_id == current_user.id
        end

        def set_comment
            @comment = Comment.includes(:article, :user).find(params[:id])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<div class="form-group">
<%= f.label :title, "Title" %>

<%= f.text_field :title, class: "form-control" %>
</div>

<div class="form-group">
<%= f.label :content, "Content" %>
<%= f.text_area :content, class: "form-control", rows: 15 %>
</div>

app/views/articles/edit.html.erb
<div class="row">
    <div class="col-lg-8">
        <%= form_for @article, :url => { :controller => 'articles', :action => 'update', :id => @article } do |f| %>
            <%= render :partial => 'form', :locals => { :f => f } %>
            <div class="article-operation row justify-content-end">
                <%= f.submit "Update", class: "btn btn-primary col-3 mr-3" %>
            </div>
        <% end %>
        <hr>
        <%= link_to 'Back to index', {:controller => 'articles', :action => 'index'}, class: "btn btn-link col-3" %>
    </div>
</div>

app/views/articles/index.html.erb
<div class="landing-cover mb-5" style="width: 100%;height: 60vh;position: relative;-webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-attachment: scroll;background-position: center;background-image: url('<%= image_path("IMAG1482.jpg")%>');">
    <div class="container h-100">
        <div class="row h-100">
            <div class="col-lg-8 col-md-10 mx-auto h-100" style="display: table; table-layout: fixed;">
                <div class="site-heading text-light text-center" style="display: table-cell;vertical-align:middle;">
                    <h1>Team blog</h1>
                    <h3>For demo only. Ruby on Rails </h3>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="col-lg-8 col-md-10 mx-auto">
<% if (@articles.count != 0) %>

        <% @articles.each do |article| %>
            <div class="post-preview">
                
                    
                    <%= link_to :controller => 'articles', :action => 'show', :id => article do %>
                        <h2 class="post-title">
                            <%= article.title %>
                        </h2>
                        <h3 class="post-subtitle">
                            <%= excerpt(article.content, "") %>
                        </h3>
                    <% end %>
                    <p class="post-meta">
                        Posted by <%= article.user.email %>
                        on <%= article.updated_at.inspect() %> 
                    </p>
                    <% if current_user.id == article.author_id %>
                        <div class="article-operation row justify-content-end">
                            <%= link_to 'Edit', {:controller => 'articles', :action => 'edit',
                            :id => article}, class: "btn btn-warning col-3 mr-1 " %>
                            <%= link_to 'Delete', article_path(article), :method => :delete, class: "btn btn-danger col-3 mr-1" %>
                        </div>
                    <% end %> 
                    
            </div>
            <hr>
        <% end %>
    
    <% end %>

    <div class="pagination justify-content-end">
    
        <%= if !(@articles.nil?) then paginate @articles, theme: 'bootstrap4' end %>

        
    </div>

    <div class="pagination paginate-info justify-content-end">
        <%= if !(@articles.nil?) then page_entries_info @articles end %>
    </div>
    

    <%= link_to 'New Article', new_article_path , class: "btn btn-primary" %>
</div>

app/views/articles/new.html.erb
<div class="row">
    <div class="col-lg-8">
        <%= form_for @article, :url => { :controller => 'articles', :action => 'create' } do |f| %>
            <%= render :partial => 'form', :locals => { :f => f } %>
            <div class="article-operation row justify-content-end">
                <%= f.submit "Create", class: "btn btn-primary col-3 mr-3" %>
            </div>
        <% end %>
        <hr>
        <%= link_to 'Back to index', {:controller => 'articles', :action => 'index'}, class: "btn btn-link col-3" %>
    </div>
</div>

app/views/articles/show.html.erb
    <div class="row"> 
        <div class="col-lg-8">
            <h1 class="mt-4">
                <%= @article.title %>
            </h1>
            <div class="lead row">
                <div class="col-4 text-left">
                    By: <%= @article.user.email %>
                </div>
                <div class="col-8 text-right">
                    Posted on <%= @article.created_at %>
                </div>
            </div>

            <hr>

            <%= @article.content %>

            <hr>

            <div class="card my-4">
                <%= render "comments/new" %>
            </div>

            <% if (@article.comments.count != 0) %>
                    <% @article.comments.each { |comment| %>
                    <div class="media mb-4">
                        <div class="media-body">
                            <h5 class="mt-5 row ">
                                <div class="text-left col-3"><%= comment.user.email %></div> 
                                <div class="text-right col-9"><%= comment.created_at %> </div>
                            </h5>
                            
                            <div class="comment-content">
                                <%= comment.content %>
                            </div>    
                                
                            <div class="comment-operation row justify-content-end">
                                <% if comment.author_id == current_user.id %>
                                    
                                        <%= link_to 'Edit comment',  edit_article_comment_path(@article, comment), class: "btn btn-warning col-3 mr-1" %>
                                        <%= link_to 'Delete comment', article_comment_path(@article, comment), :method => "delete", class: "btn btn-danger col-3 mr-3" %>
                                    
                                <% end %>
                            </div>
                        </div>
                        
                    </div>
                    <% } %> 
            <% end %>

            <hr>


            <%= link_to 'Back to index', {:controller => 'articles', :action => 'index'}, class: "btn btn-link" %>

        </div>
    </div>



    

    

app/views/comments/_form.html.erb
<div class="form-group">
    <%= f.text_area :content, class: "form-control", rows: 3 %>
    <%= f.hidden_field :article_id, :value => @article.id %>
    <%= f.hidden_field :author_id, :value => current_user.id %>
    
</div>

app/views/comments/_new.html.erb
<h5 class="card-header">
Leave a comment
</h5>
<div class="card-body">
    <%= form_for([@article, @comment]) do |f| %>
        <%= render :partial => "comments/form", :locals => {:f => f} %>
        <div class="row justify-content-end">
            <%= f.submit 'Create', class: "btn btn-primary col-3 mr-3" %>
        </div>
    <% end %>
</div>

app/views/comments/edit.html.erb
<div>
Edit comment
</div>

<%= form_for([@article, @comment], :url => { :controller => 'comments', :action => 'update'} )do |f| %>
    <%= render :partial => "form", :locals => {:f => f} %>
    <%= f.submit 'Update' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= content_for :login_status do %>
    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %> </strong>
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> | 
        <%= link_to 'Logout', destroy_user_session_path, :method => :delete, :class => 'navbar-link' %>
        
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
      <% end %>
  
  
    <% if notice %>
      <p class="alert alert-success notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    </p>
  <% end %>

  <body>
    <div class="container">
      <%= yield :login_status %>

      <%= yield %>
    </div>
  </body>
</html>